### ISSUE TITLE
PTU 3.15 Unhandled exception

### ISSUE THREAD

**Issue by iNgeon** [SCToolsfactory/SCJMapper-V2#110]
Fresh download of SCJM 2.50.0.85. Run and enable Use PTU folders
Under Mappings > select layout_all_blank > Defaults, Load and Grab! > Dump XML
Enter Mappings name layout_my_joystick_scjm-315-default-load-grab > Dump and Save my Mapping
Simply close SCJM (or make changes and save)
Launching SCJM results in an immediate crash until I delete \Roberts Space Industries\StarCitizen\PTU\USER\Client\0\Controls\Mappings\layout_my_joystick_scjm-315-default-load-grab.xml (or whatever i save it as)

As a side note, i was struggling to map quantum travel for jumping and spooling. Seems CiG has split Quantum Travel System (now under Vehicles - Seats and Operator Modes) and v_toggle_qdrive_engagement (under spaceship_quantum)

Also, don't know if I am doing anything wrong but when using SCJM to setup my stick i get strange inputs like its messing up my deadzone\something curves

----------------------------------------------------------------------------------------------
`See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Xml.XmlException: 'multiTap' is a duplicate attribute name. Line 2191, position 63.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.AttributeDuplCheck()
   at System.Xml.XmlTextReaderImpl.ParseAttributes()
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XElement.ReadElementFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XNode.ReadFrom(XmlReader reader)
   at SCJMapper_V2.Actions.ActionMapsCls.fromXML(String xml)
   at SCJMapper_V2.MainForm.Grab()
   at SCJMapper_V2.MainForm.MainForm_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
SCJMapper
    Assembly Version: 2.50.0.85
    Win32 Version: 2.50.0.85
    CodeBase: file:///C:/Port/PortableApps/SCJMapper-V2.50Build85/SCJMapper.exe
----------------------------------------
log4net
    Assembly Version: 2.0.12.0
    Win32 Version: 2.0.12.0
    CodeBase: file:///C:/Port/PortableApps/SCJMapper-V2.50Build85/log4net.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4320.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
SharpDX.XInput
    Assembly Version: 2.6.3.0
    Win32 Version: 2.6.3
    CodeBase: file:///C:/Port/PortableApps/SCJMapper-V2.50Build85/SharpDX.XInput.DLL
----------------------------------------
SharpDX.DirectInput
    Assembly Version: 2.6.3.0
    Win32 Version: 2.6.3
    CodeBase: file:///C:/Port/PortableApps/SCJMapper-V2.50Build85/SharpDX.DirectInput.DLL
----------------------------------------
SharpDX
    Assembly Version: 2.6.3.0
    Win32 Version: 2.6.3
    CodeBase: file:///C:/Port/PortableApps/SCJMapper-V2.50Build85/SharpDX.DLL
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

`

**Comment by bm98** [comment]
Yep – CIG invented the Rebind new… and uses it  in the empty template –

The prog does not handle this one properly as it was used to be AddBind not multiple Rebind

<action  name="v_shield_raise_level_up"  >
                <rebind  device="gamepad"  ActivationMode="press"  input=" "  />
                <rebind  device="keyboard"  ActivationMode="press"  input=" "  />
                <rebind  device="mouse"  ActivationMode="press"  input=" "  />
                <rebind  device="joystick"  ActivationMode="press"  input="js1_ "  />
                <rebind  device="joystick"  ActivationMode="press"  input="js2_ "  />
                <rebind  device="joystick"  ActivationMode="press"  input="js3_ "  />
</action>

And it was supposed to be 

 <action name="v_shield_raise_level_up">
                <rebind input="xi1_ " multiTap="1"  />
                <addbind input="kb1_ " multiTap="1"  />
                <addbind input="mo1_ " multiTap="1"  />
                <addbind input="js1_ " multiTap="1"  />
                <addbind input="js2_ " multiTap="1" ActivationMode="press"  />
                <addbind input="js3_ " multiTap="1" ActivationMode="press"  />
</action>

In the past (long ago..)


So we have to update again… as the program put’s out the wrong XML  for the 2 and 3rd js when there is an ActivationMode set

                <addbind input="js2_ " multiTap="1" ActivationMode="press" multiTap = "1"  />
                <addbind input="js3_ " multiTap="1" ActivationMode="press" multiTap = "1"  />

The multiTap appears twice in a row..

Now the program starts with the last used file which is messed up –

Go to the PTU Mappings folder   …\StarCitizen\PTU\USER\Client\0\Controls\Mappings

And either delete the offending file (last used one) – then the program starts OK


You cannot use the Blank default for the moment as it will not be treated properly from start and causes all kind of problems throughout

**Comment by SupremeTechnopriest** [comment]
Any plans to update the program for 3.15?
