### ISSUE TITLE
Crash when launching Device Tuning

### ISSUE THREAD

**Issue by sp4ke** [SCToolsfactory/SCJMapper-V2#26]
Dump:

```

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at SCJMapper_V2.FormJSCalCurve.Application_Idle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at SCJMapper_V2.MainForm.btJSTuning_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34011 built by: FX45W81RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
SCJMapper
    Assembly Version: 2.10.0.40
    Win32 Version: 2.10.0.40
    CodeBase: file:///D:/Hotas/SCJMapper-V2.10beta1Build40/SCJMapper.exe
----------------------------------------
log4net
    Assembly Version: 1.2.13.0
    Win32 Version: 1.2.13.0
    CodeBase: file:///D:/Hotas/SCJMapper-V2.10beta1Build40/log4net.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
Ionic.Zip.Reduced
    Assembly Version: 1.9.1.8
    Win32 Version: 1.9.1.8
    CodeBase: file:///D:/Hotas/SCJMapper-V2.10beta1Build40/Ionic.Zip.Reduced.DLL
----------------------------------------
SharpDX.DirectInput
    Assembly Version: 2.6.3.0
    Win32 Version: 2.6.3
    CodeBase: file:///D:/Hotas/SCJMapper-V2.10beta1Build40/SharpDX.DirectInput.DLL
----------------------------------------
SharpDX
    Assembly Version: 2.6.3.0
    Win32 Version: 2.6.3
    CodeBase: file:///D:/Hotas/SCJMapper-V2.10beta1Build40/SharpDX.DLL
----------------------------------------
SharpDX.XInput
    Assembly Version: 2.6.3.0
    Win32 Version: 2.6.3
    CodeBase: file:///D:/Hotas/SCJMapper-V2.10beta1Build40/SharpDX.XInput.DLL
----------------------------------------
OpenTK
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.1589.5942
    CodeBase: file:///D:/Hotas/SCJMapper-V2.10beta1Build40/OpenTK.DLL
----------------------------------------
System.Windows.Forms.DataVisualization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.DataVisualization/v4.0_4.0.0.0__31bf3856ad364e35/System.Windows.Forms.DataVisualization.dll
----------------------------------------
OpenTK.GLControl
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.1589.5942
    CodeBase: file:///D:/Hotas/SCJMapper-V2.10beta1Build40/OpenTK.GLControl.DLL
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

```

**Comment by jwvanderbeck** [comment]
Having this same problem, not sure if the error or cause is the same.  Latest version just downloaded today.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.OverflowException: Array dimensions exceeded supported range.
   at SCJMapper_V2.OGL.BezierInterpolation..ctor(IEnumerable`1 points, Int32 resolution)
   at SCJMapper_V2.OGL.BezierSeries.CalcCurve(Single[] cout)
   at SCJMapper_V2.OGL.BezierSeries.Invalidate(Control owner)
   at System.Windows.Forms.Control.OnResize(EventArgs e)
   at OpenTK.GLControl.OnResize(EventArgs e)
   at OpenTK.GLControl.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Control.WmCreate(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.UserControl.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4042.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
SCJMapper
    Assembly Version: 2.42.0.77
    Win32 Version: 2.42.0.77
    CodeBase: file:///E:/Games/Roberts%20Space%20Industries/StarCitizen/SCJMapper-V2.42Build77/SCJMapper.exe
----------------------------------------
log4net
    Assembly Version: 1.2.13.0
    Win32 Version: 1.2.13.0
    CodeBase: file:///E:/Games/Roberts%20Space%20Industries/StarCitizen/SCJMapper-V2.42Build77/log4net.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4001.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4042.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4042.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
SharpDX.XInput
    Assembly Version: 2.6.3.0
    Win32 Version: 2.6.3
    CodeBase: file:///E:/Games/Roberts%20Space%20Industries/StarCitizen/SCJMapper-V2.42Build77/SharpDX.XInput.DLL
----------------------------------------
SharpDX.DirectInput
    Assembly Version: 2.6.3.0
    Win32 Version: 2.6.3
    CodeBase: file:///E:/Games/Roberts%20Space%20Industries/StarCitizen/SCJMapper-V2.42Build77/SharpDX.DirectInput.DLL
----------------------------------------
SharpDX
    Assembly Version: 2.6.3.0
    Win32 Version: 2.6.3
    CodeBase: file:///E:/Games/Roberts%20Space%20Industries/StarCitizen/SCJMapper-V2.42Build77/SharpDX.DLL
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
OpenTK
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.1589.5942
    CodeBase: file:///E:/Games/Roberts%20Space%20Industries/StarCitizen/SCJMapper-V2.42Build77/OpenTK.DLL
----------------------------------------
System.Windows.Forms.DataVisualization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3815.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.DataVisualization/v4.0_4.0.0.0__31bf3856ad364e35/System.Windows.Forms.DataVisualization.dll
----------------------------------------
OpenTK.GLControl
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.1589.5942
    CodeBase: file:///E:/Games/Roberts%20Space%20Industries/StarCitizen/SCJMapper-V2.42Build77/OpenTK.GLControl.DLL
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by bm98** [comment]
I would need the xml file you load and then want to go for the options dialog.
It is an unassigned obj in c# - hence I need the one file that causes it

**Comment by jwvanderbeck** [comment]
Hmm not sure if there is one yet? I just opened the program fresh, then rebound the pitch and roll axis to a joystick, and clicked the tuning option.  Everything else was default.

Still learning the program, and just pushing buttons and flipping switches and seeing what happens :)

**Comment by bm98** [comment]
That should work... does it here at least but things are sometimes different ...
Either perform 'Reset... defaults' from the menu and then try again or..
If you do as mentioned and then instead of using the Tuning Dialog just hit the Red 'Dump XML' and then save that file and attach it here. (Saving is right click in the XML window and then use Save As..  'something.xml'

**Comment by jwvanderbeck** [comment]
1. Reset -> Defaults
2. Show -> Device Tuning Dialog
3. Crash

Attaching XML zipped up (wouldn't let me upload it as xml)

[bug.zip](https://github.com/SCToolsfactory/SCJMapper-V2/files/4054720/bug.zip)

**Comment by bm98** [comment]
It does not create issues here but also I cannot figure out why it crashes at this point..
so we may dig one deeper:

 You will find ‘log4net.config.OFF’ in the folder where the prog is located.
 Rename it to ‘log4net.config’ and run the program again and create the crash.
 Then look for a file named ‘trace.log’ in that folder and
 send this via Git along with a description of your system i.e. Win 7/10 or whatever 
The Joystick(s) I've seen are 4 with the Rudder being used for the pitch, yaw and roll (js1_)
May be the logfile gives a hint where it get lost...
