### ISSUE TITLE
"Unhandled exception has occurred in your application."

### ISSUE THREAD

**Issue by svdb** [SCToolsfactory/SCJMapper-V2#55]
Just launching SCJMapper-V2 on Windows 7 P1 - 64bit Enterprise edition produces the following message in a .NET Framework popup dialog box.

This also happens when I "load and grab" one of my xml config files (after having clicked "Continue" on the dialog box).
The xml is then visible on the right, but the treeview on the left is missing/blank.

I have .NET 4.6.1 and did a "repair" on it but it didn't change anything.
All Windows Update patches installed for .NET

```
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at SCJMapper_V2.ActionTree.LoadProfileTree(String defaultProfileName, Boolean applyDefaults)
   at SCJMapper_V2.MainForm.InitActionTree(Boolean addDefaultBinding)
   at SCJMapper_V2.MainForm.InitDirectInput()
   at SCJMapper_V2.MainForm.MainForm_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1076.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
SCJMapper
    Assembly Version: 2.27.0.61
    Win32 Version: 2.27.0.61
    CodeBase: file:///H:/SCJMapper-V2.27Build61/SCJMapper.exe
----------------------------------------
log4net
    Assembly Version: 1.2.13.0
    Win32 Version: 1.2.13.0
    CodeBase: file:///H:/SCJMapper-V2.27Build61/log4net.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1075.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1067.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1068.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
SharpDX.DirectInput
    Assembly Version: 2.6.3.0
    Win32 Version: 2.6.3
    CodeBase: file:///H:/SCJMapper-V2.27Build61/SharpDX.DirectInput.DLL
----------------------------------------
SharpDX
    Assembly Version: 2.6.3.0
    Win32 Version: 2.6.3
    CodeBase: file:///H:/SCJMapper-V2.27Build61/SharpDX.DLL
----------------------------------------
SharpDX.XInput
    Assembly Version: 2.6.3.0
    Win32 Version: 2.6.3
    CodeBase: file:///H:/SCJMapper-V2.27Build61/SharpDX.XInput.DLL
----------------------------------------
Ionic.Zip.Reduced
    Assembly Version: 1.9.1.8
    Win32 Version: 1.9.1.8
    CodeBase: file:///H:/SCJMapper-V2.27Build61/Ionic.Zip.Reduced.DLL
----------------------------------------
```

**Comment by bm98** [comment]
Pls look into #51  Exception reading defaultProfile in SC PTU2.6.2 for a workaround

**Comment by bm98** [comment]
Pls look into #51 Exception reading defaultProfile in SC PTU2.6.2 for a workaround

**Comment by svdb** [comment]
Thanks! The "defaultProfile" file workaround in #51 worked.

Unrelated: I tried compiling the project but couldn't unless I changed a return value Boolean to boolean somewhere (forgot which class), and m_hwnd to m_hwnd.Handle in MouseCls, KeyboardCls and JoystickCls ctors.

**Comment by bm98** [comment]
:)  This is when you use the latest DXsharp binaries – however I found other issues when I tried to update OpenTK - latest so I stick with the current version of the external libraries.

If you want to get the package with the current libs let me know I can upload them to my site and you may get them there.

 

BTW just posted the new version – though you may use it with care … and in parallel with the current build.

 

Regs

Martin
